### ISSUE TITLE
[Feature] Leaderboard System

### ISSUE THREAD

**Issue by grahhnt** [AlpsBTE/Plot-System#101]
- Lifetime, Monthly, Daily holographic leaderboard in the spawn area
- Database-backed config for payout notices ($xxx for `#1` in monthly)
- Action bar message with position & top percentage or top `#100`

Reviews Table:
- Add rejected (or general review status) column
- Add total points awarded column
  Future proofing for weighted points awarded

**Comment by grahhnt** [comment]
I am working on this

**Comment by Cinnazeyy** [comment]
correction: we save a rejected plot by setting the total score as null in the database and reading it as -1 in our code

**Comment by MineFact** [comment]
@Cinnazeyy so many of the new features already broke the backwards compatibility with the 3.0 update and as far as I remember @LordTuxn already agreed with us that for this update don't need to ensure 100% backwards compatibility. If not please correct me.

@grahhnt is working on this new feature because we need to wait for the PlotSystemAPI to get finished before we can release the beta on the network. He can't really help with that and thats why he is working on new features in the meanwhile.
