### ISSUE TITLE
[Feature] - Improved reviewing system

### ISSUE THREAD

**Issue by StoneMcYT** [AlpsBTE/Plot-System#87]
**Is your feature request related to a problem? Please describe.**
I find it a annoying when a plot requires X number of points to be approved 
and bellow X number to be denied as me and a couple of reviewers see builders doing well in certain aspects whilest certain are not eg a very good block palette but the accuracy is a off for a wall or something like that 

**Describe the solution you'd like**
A reject/accept button

**Comment by LordTuxn** [comment]
The review system is based on the points system. It doesn't really make sense to remove the "points per category" as it is a great way to give feedback to the builders. The improved review system in V3.0 will show how many points are needed to approve or reject a plot, as well as a short description on how the system works. Even though it would be technically possible to implement these buttons I don't think it really makes sense since it would just give 8 points for rejection and 20 points for approvement, which can be a bit confusing sometimes for the builder. Therefore I will close this issue.
